# Generated by Django 4.2.5 on 2023-09-18 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_category_product_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="parent",
            new_name="category",
        ),
    ]
