# Generated by Django 4.2.5 on 2023-09-18 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_parent_category_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tree_id",
        ),
    ]
