# Generated by Django 4.2.5 on 2023-09-25 20:45

import apps.product.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alt_text", models.CharField(max_length=100)),
                ("url_image", models.ImageField(upload_to="products")),
                ("order", apps.product.fields.OrderField(blank=True)),
                (
                    "productline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_line",
                        to="product.productline",
                    ),
                ),
            ],
        ),
    ]
