# Generated by Django 4.2.5 on 2023-09-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_rename_category_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
