# Generated by Django 4.2.5 on 2023-09-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="url_image",
            field=models.ImageField(default="test.jpg", upload_to="products"),
        ),
    ]
