# Generated by Django 4.2.5 on 2023-09-25 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_productimage_url_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
