# Generated by Django 4.2.5 on 2026-03-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_atribute_atributevalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atributevalue",
            old_name="att_value",
            new_name="attribute_value",
        ),
        migrations.AddField(
            model_name="atributevalue",
            name="attribute",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_value",
                to="product.atribute",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductLineAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_value_av",
                        to="product.atributevalue",
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_value_pl",
                        to="product.productline",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute_value", "product_line")},
            },
        ),
        migrations.AddField(
            model_name="productline",
            name="attribute_values",
            field=models.ManyToManyField(
                through="product.ProductLineAttributeValue", to="product.atributevalue"
            ),
        ),
    ]
