# Generated by Django 4.2.5 on 2026-03-26 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_att_value_atributevalue_attribute_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productline",
            old_name="attribute_values",
            new_name="attribute_value",
        ),
    ]
