# Generated by Django 4.2.5 on 2026-04-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_rename_attribute_values_productline_attribute_value"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Atribute",
            new_name="Attribute",
        ),
        migrations.RenameModel(
            old_name="AtributeValue",
            new_name="AttributeValue",
        ),
        migrations.AlterField(
            model_name="productline",
            name="attribute_value",
            field=models.ManyToManyField(
                related_name="product_line_attribute_value",
                through="product.ProductLineAttributeValue",
                to="product.atributevalue",
            ),
        ),
    ]
