# Generated by Django 4.2.5 on 2026-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_rename_atribute_attribute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="attribute_value",
            field=models.ManyToManyField(
                related_name="product_line_attribute_value",
                through="product.ProductLineAttributeValue",
                to="product.attributevalue",
            ),
        ),
    ]
